version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:22
    volumes:
      - ..:/workspaces/webnc
    command: sleep infinity

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: newsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: